---
services:
  logstash:
    build:
      context: ./logstash
      args:
        ELASTIC_STACK_VERSION: ${ELASTIC_STACK_VERSION}
    container_name: logstash
    restart: unless-stopped
    user: "1001"
    volumes:
      - ${DOCKER_HOME}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ${DOCKER_HOME}/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ${DOCKER_HOME}/logstash/config/log4j2.properties:/usr/share/logstash/config/log4j2.properties
      - ${DOCKER_HOME}/logstash/pipeline:/usr/share/logstash/pipeline
      - ${DOCKER_HOME}/logstash/files:/usr/share/logstash/files
      - logstash_data:/usr/share/logstash/data
    environment:
      LS_PIPELINE_WORKERS: ${LS_PIPELINE_WORKERS}
      LS_LOG_LEVEL: ${LS_LOG_LEVEL}
      LS_MONITORING_ENABLED: ${LS_MONITORING_ENABLED}
      LS_MONITORING_CLUSTER_UUID: ${LS_MONITORING_CLUSTER_UUID}
      LS_CENTRALIZED_MGMT: ${LS_CENTRALIZED_MGMT:-false}
      LS_API_USER: ${LS_API_USER}
      LS_API_PW: ${LS_API_PW}
      ES_ENDPOINT: ${ES_ENDPOINT}
      ES_API_KEY_ID: ${ES_API_KEY_ID}
      ES_API_KEY: ${ES_API_KEY}
      OPENSKY_API_USER: ${OPENSKY_API_USER}
      OPENSKY_API_PW: ${OPENSKY_API_PW}
      OPENSKY_API_CLIENT_ID: ${OPENSKY_API_CLIENT_ID}
      OPENSKY_API_CLIENT_SECRET: ${OPENSKY_API_CLIENT_SECRET}


volumes:
  logstash_data:
